name: Feature Branch Workflow

on:
  push:
    branches:
      - "feature/**"
    paths:
      - "force-app/**"

env:
  GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
  GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
  SF_ORG__SIT__AUTH_URL: ${{ secrets.SF_ORG__SIT__AUTH_URL }}

jobs:
  Validate_Against_SIT:
    runs-on: ubuntu-latest
    container:
      image: salesforce/salesforcedx:latest-full
      options: --user 0:0
    steps:
      - uses: actions/checkout@v1

      - name: Run Validation against SIT
        run: force:auth:sfdxurl:store --sfdxurlfile=./SF_ORG__SIT__AUTH_URL.txt --setalias=DevHub --setdefaultdevhubusername
        run: sfdx force:source:deploy --sourcepath force-app/main/default --checkonly --testlevel NoTestRun --targetusername DevHub
